### ISSUE TITLE
NOS Api deployement

### ISSUE THREAD

**Issue by blascokoa** [blascokoa/nOSpoll#6]
We are assuming about the NOS api can be deployed into the neo SC, but I NEVER see an sc for a NOS dApp included into a SC.

Just asked to discord channel if that is doable or not.

**Comment by krishislegend** [comment]
thats why my smart contract never included NOS API. my assumption and always was that the smart contract should be deployed independantly and we should use NOS API from web to call our NEO smart contract and thats my assumption.
